// Mocks generated by Mockito 5.4.6 from annotations
// in myapp/test/src/features/doses/presentation/providers/test_dose_provider.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:myapp/src/features/doses/data/models/dose.dart' as _i5;
import 'package:myapp/src/features/doses/data/repositories/dose_repository.dart'
    as _i3;
import 'package:myapp/src/features/medication/models/medication.dart' as _i6;
import 'package:sqflite/sqflite.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeDatabase_0 extends _i1.SmartFake implements _i2.Database {
  _FakeDatabase_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [DoseRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockDoseRepository extends _i1.Mock implements _i3.DoseRepository {
  MockDoseRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.Database get database => (super.noSuchMethod(
        Invocation.getter(#database),
        returnValue: _FakeDatabase_0(
          this,
          Invocation.getter(#database),
        ),
      ) as _i2.Database);

  @override
  _i4.Future<void> addDose(_i5.Dose? dose) => (super.noSuchMethod(
        Invocation.method(
          #addDose,
          [dose],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> updateDose(_i5.Dose? dose) => (super.noSuchMethod(
        Invocation.method(
          #updateDose,
          [dose],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<List<_i5.Dose>> getDosesForDay(DateTime? date) =>
      (super.noSuchMethod(
        Invocation.method(
          #getDosesForDay,
          [date],
        ),
        returnValue: _i4.Future<List<_i5.Dose>>.value(<_i5.Dose>[]),
      ) as _i4.Future<List<_i5.Dose>>);

  @override
  _i4.Future<List<_i5.Dose>> getAllDoses() => (super.noSuchMethod(
        Invocation.method(
          #getAllDoses,
          [],
        ),
        returnValue: _i4.Future<List<_i5.Dose>>.value(<_i5.Dose>[]),
      ) as _i4.Future<List<_i5.Dose>>);

  @override
  _i4.Future<void> createDosesForMedication(_i6.Medication? medication) =>
      (super.noSuchMethod(
        Invocation.method(
          #createDosesForMedication,
          [medication],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> deleteDosesForMedication(int? medicationId) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteDosesForMedication,
          [medicationId],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}
