// Mocks generated by Mockito 5.4.6 from annotations
// in myapp/test/medication_provider_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:myapp/src/database/database_helper.dart' as _i2;
import 'package:myapp/src/features/medication/data/models/medication.dart'
    as _i5;
import 'package:myapp/src/features/medication/data/repositories/medication_repository.dart'
    as _i3;
import 'package:myapp/src/features/medication/presentation/services/dose_service.dart'
    as _i6;
import 'package:myapp/src/features/medication/presentation/services/notification_service.dart'
    as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeDatabaseHelper_0 extends _i1.SmartFake
    implements _i2.DatabaseHelper {
  _FakeDatabaseHelper_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [MedicationRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockMedicationRepository extends _i1.Mock
    implements _i3.MedicationRepository {
  MockMedicationRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.DatabaseHelper get dbHelper => (super.noSuchMethod(
        Invocation.getter(#dbHelper),
        returnValue: _FakeDatabaseHelper_0(
          this,
          Invocation.getter(#dbHelper),
        ),
      ) as _i2.DatabaseHelper);

  @override
  _i4.Future<int> addMedication(_i5.Medication? medication) =>
      (super.noSuchMethod(
        Invocation.method(
          #addMedication,
          [medication],
        ),
        returnValue: _i4.Future<int>.value(0),
      ) as _i4.Future<int>);

  @override
  _i4.Future<void> updateMedication(_i5.Medication? medication) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateMedication,
          [medication],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> deleteMedication(int? id) => (super.noSuchMethod(
        Invocation.method(
          #deleteMedication,
          [id],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<_i5.Medication?> getMedication(int? id) => (super.noSuchMethod(
        Invocation.method(
          #getMedication,
          [id],
        ),
        returnValue: _i4.Future<_i5.Medication?>.value(),
      ) as _i4.Future<_i5.Medication?>);

  @override
  _i4.Future<List<_i5.Medication>> getAllMedications() => (super.noSuchMethod(
        Invocation.method(
          #getAllMedications,
          [],
        ),
        returnValue: _i4.Future<List<_i5.Medication>>.value(<_i5.Medication>[]),
      ) as _i4.Future<List<_i5.Medication>>);
}

/// A class which mocks [DoseService].
///
/// See the documentation for Mockito's code generation for more information.
class MockDoseService extends _i1.Mock implements _i6.DoseService {
  MockDoseService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<void> createDosesForMedication(_i5.Medication? medication) =>
      (super.noSuchMethod(
        Invocation.method(
          #createDosesForMedication,
          [medication],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}

/// A class which mocks [NotificationService].
///
/// See the documentation for Mockito's code generation for more information.
class MockNotificationService extends _i1.Mock
    implements _i7.NotificationService {
  MockNotificationService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<void> init() => (super.noSuchMethod(
        Invocation.method(
          #init,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> requestPermissions() => (super.noSuchMethod(
        Invocation.method(
          #requestPermissions,
          [],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> scheduleNotifications(
    _i5.Medication? medication,
    String? title,
    String? body,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #scheduleNotifications,
          [
            medication,
            title,
            body,
          ],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<void> cancelNotifications(int? medicationId) =>
      (super.noSuchMethod(
        Invocation.method(
          #cancelNotifications,
          [medicationId],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);
}
